name: publish-package
on:
  workflow_dispatch:
    branches:
      - main
      - master
    inputs:
      semver:
        description: 'major, minor or patch'
        required: true
        default: 'patch'
      version:
        description: 'tag for NPM'
        required: true
        default: 'latest-v2'
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
      - run: . ./build-script/verify-branch.sh ${GITHUB_REF##*/}
      - run:  |
          npm install
          npm run release:${{ github.event.inputs.semver }}
          git config --global user.name ${{ github.actor }}
          npm run commit && npm run git-tag
      - run: npm publish --tag ${{ github.event.inputs.version }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
